src/config/routes.rb
# frozen_string_literal: true
# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :symptoms
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  get 'home/results'
  get 'home/arms'
  get 'home/core'
  get 'home/legs'
  get 'home/head'

  get 'home/symptoms'
  root 'home#index'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  #devise_for :users  
  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/models/app_config.rb
# frozen_string_literal: true

# global app configuration model

# Fields:
# - name: string
# - logo_url: string
class AppConfig < ApplicationRecord
  # make sure all fields exist
  validates :name, :logo_url, presence: true

  # make sure app name isn't empty
  # logo can be empty. That's not a big teal tbh.
  validates_length_of :name, minimum: 1
end

src/app/models/application_record.rb
# frozen_string_literal: true

# Parent class of all models
# Edit to add attributes and behaviors to all models
# TCNJ: You probably won't touch this
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/symptom.rb
class Symptom < ApplicationRecord
end

src/app/models/user.rb
# frozen_string_literal: true

# Represents a user of the web application
class User < ApplicationRecord
  # Devise is a premade system for managing logins
  # You don't need to do login yourself. It's done for you.
  # TCNJ: don't edit the login system.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # If someone tried to pretend to be someone else, an error occurs for them
  protect_from_forgery with: :exception
  # See if the current user is logged in
end

src/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
  def arms    #Arms
    @symptoms = Symptom.where(sym_location: 'Arms') #Finds all Arm related Symptoms
    if params[:sym_desc]
      @symptom = Symptom.find_by(sym_desc: params[:sym_desc]) 
      @chosen_symptom = @symptom.solution #Assigns Symptom Solution
      @severity = @symptom.sym_severity #Assigns Symptom Severity
    end
  end
  #def legs
  #  @symptoms = Symptom.where(sym_location: 'Legs')
  #  if params[:sym_desc]
  #    @chosen_symptom = Symptom.find_by(sym_desc: params[:sym_desc]).solution
  #  end
  #end
def legs
  @symptoms = Symptom.where(sym_location: 'Legs') #Finds all Leg related Symptoms
    if params[:sym_desc]
      @symptom = Symptom.find_by(sym_desc: params[:sym_desc])
      @chosen_symptom = @symptom.solution #Assigns Symptom Solution
      @severity = @symptom.sym_severity #Assigns Symptom Severity
    end
end
  #def core
  #  @symptoms = Symptom.where(sym_location: 'Core')
  #  if params[:sym_desc]
  #    @chosen_symptom = Symptom.find_by(sym_desc: params[:sym_desc]).solution
  #  end
  #end
  def core
    @symptoms = Symptom.where(sym_location: 'Core') #Finds all Core related Symptoms
      if params[:sym_desc]
        @symptom = Symptom.find_by(sym_desc: params[:sym_desc])
        @chosen_symptom = @symptom.solution #Assigns Symptom Solution
        @severity = @symptom.sym_severity #Assigns Symptom Severity
      end
  end
  def head
    @symptoms = Symptom.where(sym_location: 'Head') #Finds all Head related Symptoms
      if params[:sym_desc]
        @symptom = Symptom.find_by(sym_desc: params[:sym_desc])
        @chosen_symptom = @symptom.solution #Assigns Symptom Solution
        @severity = @symptom.sym_severity #Assigns Symptom Severity
      end
  end


  
end

src/app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  #before_action :set_symptom, only: %i[ show edit update destroy ]
  # GET /symptoms or /symptoms.json

  def index #Initialize Symptom Information
    @symptoms = Symptom.all
    if params[:sym_desc]
      @symptom = Symptom.find_by(sym_desc: params[:sym_desc]) #Locate Symptom Information
      @chosen_symptom = @symptom.solution
      @severity = @symptom.sym_severity
    end

  end
  # GET /symptoms/1 or /symptoms/1.json
  def show
  end
  # GET /symptoms/new
  def new
    @symptom = Symptom.new
  end
  # GET /symptoms/1/edit
  def edit
  end
  # POST /symptoms or /symptoms.json
  #def create
  #  @symptom = Symptom.new(symptom_params)
  #  respond_to do |format|
  #    if @symptom.save
  #      format.html { redirect_to symptom_url(@symptom), notice: "Symptom was successfully created." }
  #      format.json { render :show, status: :created, location: @symptom }
  #    else
  #      format.html { render :new, status: :unprocessable_entity }
  #      format.json { render json: @symptom.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end
  # PATCH/PUT /symptoms/1 or /symptoms/1.json
  def update
    respond_to do |format|
      if @symptom.update(symptom_params)
        format.html { redirect_to symptom_url(@symptom), notice: "Symptom was successfully updated." }
        format.json { render :show, status: :ok, location: @symptom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /symptoms/1 or /symptoms/1.json
  def destroy
    @symptom.destroy
    respond_to do |format|
      format.html { redirect_to symptoms_url, notice: "Symptom was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_symptom
      @symptom = Symptom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def symptom_params
      params.require(:symptom).permit(:sym_desc, :sym_severity, :sym_location, :solution)    
    end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper functions made here are accessable in all views
# for example, app_name is now accessable to all views
module ApplicationHelper
  def app_name
    "Off Day"
  end

  private

  def app_config
    AppConfig.first
  end
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods accessable for views within the home folder
module HomeHelper
end

src/app/helpers/symptoms_helper.rb
module SymptomsHelper
end

src/app/views/home/_erb.html.erb
<h2>ERB basics</h2>
<p>
  <%# You'll notice the tags are in tags. It's because otherwise %>
  <%# they will be parsed as code and I want plain text here. %>
  To run ruby code, put it in a tag formatted like this:
  <br>
  <mark><%% app_name() %></mark> -> <% app_name() %>
  <br>
  However, that won't change the HTML sent to the client. In fact, even if
  we tried to write something that would be part of the document like this
  <br>
  <mark><%% 'Hello, world!' %></mark> -> <% 'Hello, world!' %>
  <br>
  Nothing happens still? This is because while rails inputs the return value of 
  a block of code like this into the document, it only does so if we tell
  the language to do so. We do that like this. Add an = to the front of
  the block.
  <br>
  <mark><%%= 'Hello, world!' %></mark> -> <%= 'Hello, world!' %>
  <br>
  And success! However, in doing so, we found something important.
  If you want to run some code like an if around HTML depending on if the 
  user is logged in or not, use <mark><%% if %> ... <%% else %> ... <%% end %></mark>.
  None of these tags will output anything since there's no =, so you
  can do things like this. However, if you do want to output something,
  make sure to use the equal sign at the front, or you'll be confused as
  to why nothing is printing!
  <br>
  Oh, and comments are like this. <mark><%%# Hiya! %></mark>. They will not be
  written to the HTML file sent to the user.
</p>
<h2>Writing good html.erb files</h2>
<p>
  Here's the golden rule of erb: don't process data in the erb file!
  There's nothing to stop you from processing information within the view
  itself, but this is very bad practice for several reasons.
</p>
<p>
  The main reason is simple. MVC. Model, View, Controller. A view should
  NOT be fetching its own information or manipulating models. That's the 
  controller's job. Keeping these tasks seperate will make your view
  files highly readable. Speaking from experience, Software Engineering
  projects can become complex due to (unavoidable, you're learning!)
  inexperience with web development and the MVC model. Doing your best to
  follow those guidelines will help you substancially in the last few
  assignments of the classs.
</p>

src/app/views/home/_filetree.html.erb
<h2>File Structure</h2>
<p>
  The rails file structure is strange. Please be patient. You'll learn it in time.
</p>
<p>
  Note: The following has important sections bolded and underlined. The
  other sections can be largely ignored unless you have some specific need
  for them. <i>Not automatically made</i> means that a brand new rails 
  project will not contain this file. Some things were made to give
  you a starting point for the class.
</p>
<pre>
tcnj-rails-image/app
├── <b><mark>assets (Holds images, CSS, and javascript)</mark></b> 
│   ├── <mark><b>config</b></mark>
│   │   └── <mark><b>manifest.js (how to assemble the things in assets)</b></mark>
│   ├── <mark><b>images (any statically available images)</b></mark>
│   ├── <mark><b>javascripts</b></mark>
│   │   └── <mark><b>application.js (global javascript)</b></mark>
│   └── <mark><b>stylesheets</b></mark>
│       ├── <mark><b>application.scss (global css)</b></mark>
│       └── <mark><b>home.scss (controller specific css [not automatically made])</b></mark>
├── channels
│   └── application_cable
│       ├── README.md
│       ├── channel.rb
│       └── connection.rb
├── <mark><b>controllers (The C of MVC. Handles data manipulation and handling.)</mark></b>
│   ├── <mark><b>application_controller.rb (Superclass of all controllers)</mark></b>
│   ├── concerns
│   └── <mark><b>home_controller.rb (Controller for the home pages [not automatically made])</mark></b>
├── <mark><b>helpers (Any helper methods wanted inside of erb files)</b></mark>
│   ├── <mark><b>application_helper.rb (Superclass of all helpers</mark></b>
│   └── <mark><b>home_helper.rb (Helpers specific to views within the home folder [not automatically made])</mark></b>
├── javascript (this is webpack specific and will probably be ignored)
│   ├── channels
│   │   ├── consumer.js
│   │   └── index.js
│   └── packs
│       └── application.js
├── <mark><b>jobs (Workloads to be run in the background)</mark></b>
│   └── <mark><b>application_job.rb (Superclass of all jobs)</b></mark>
├── mailers
│   └── application_mailer.rb
├── <mark><b>models (The M of MVC, storing and representing information)</mark></b>
│   ├── <mark><b>app_config.rb (A model for strong global settings [not automatically made])</mark></b>
│   ├── <mark><b>application_record.rb (The superclass of all models)</mark></b>
│   ├── concerns
│   └── <mark><b>user.rb (A model representing a website user [not automatically made])</mark></b>
└── <mark><b>views (The V of MVC, defining how information is presented to a user)</mark></b>
    ├── <mark><b>home (Views for the home controller [not automatically made])</mark></b>
    │   ├── _erb.html.erb (A piece of the index page)
    │   ├── _filetree.html.erb (A piece of the index page)
    │   ├── _mvc.html.erb (A piece of the index page)
    │   └── <mark><b>index.html.erb (The webpage you're staring at)</mark></b>
    └── <mark><b>layouts (Special views that contain the common outside of all pages)</mark></b>
        ├── <mark><b>application.html.erb (The content displayed on <i>every</i></mark></b>
        ├── mailer.html.erb
        └── mailer.text.erb
</pre>
</p>

src/app/views/home/_mvc.html.erb
<h2>The MVC Model of web development</h2>
<p>
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/MVC-Process.svg/400px-MVC-Process.svg.png">
</p>
<p>
  <b>Model:</b> data organization<br>
  <b>View:</b> the presentation of information to the user<br>
  <b>Controller:</b> the manipulation and overseeing of information and access to it
</p>
<p>
  These three categories make up the design of practically every application,
  desktop or internet enabled. It's the seperation of these tasks that
  keeps an application easy to maintain, write, and read. Please make sure
  to understand these categories before working with rails. If you don't 
  recall seeing these terms before, check the class slides.
</p>
<p>
  For more information, see <a href="https://www.wikiwand.com/en/Model%E2%80%93view%E2%80%93controller">Wikipedia</a>.
</p>

src/app/views/home/arms.html.erb
  <h1>Body Part: Arms</h1>
<%#= link_to "Arms", home_arms_path, class:"btn btn-secondary"%>
<div class = "center">
    <%= image_tag "arms3.png", :style => "float: left; margin: 100px 100px 100px", height: 720 %>
<br><br>
    
  <%= form_with model: @symptom, method: :get do |form| %> 
    <%= form.select :sym_desc, options_for_select(@symptoms.collect{|u| [u.sym_desc]})%>
    <%= form.submit "Search" %>
  <% end %>
  <p>
 <strong><font size = "5"> Solution:
  <strong>
    <%= @chosen_symptom %>
  </strong>
  </p>
  <p>
  Severity Level:
  <strong>
    <%= @severity %>
  </strong>
  </p>
</div>
<%= link_to "Reset", home_arms_path, :style => "float: right; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block"%>
<%#= link_to "index", home_index_path, :style => "float: center; margin: 300px 100px 10px", class:"btn btn-secondary"%>

src/app/views/home/core.html.erb
<h1>Body Part: Core</h1>

<div class = "center">
    <%= image_tag "core3.png", :style => "float: left; margin: 100px 100px 100px", height: 720 %>
<br><br>
      <%= form_with model: @symptom, method: :get do |form| %> 
    <%= form.select :sym_desc, options_for_select(@symptoms.collect{|u| [u.sym_desc]})%>
    <%= form.submit "Search" %>
  <% end %>
  
  <p>
 <strong><font size = "5"> Solution:
  <strong>
    <%= @chosen_symptom %>
  </strong>
  </p>

  <p>
  Severity Level:
  <strong>
    <%= @severity %>
  </strong>
  </p>
  <%= link_to "Reset", home_core_path, :style => "float: right; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block"%>
</div>

src/app/views/home/head.html.erb
<h1>Body Part: Head</h1>

<div class = "text-right">
    <%= image_tag "head3.png", :style => "float: left; margin: 100px 100px 100px", height: 720 %>
<br><br>
     <%= form_with model: @symptom, method: :get do |form| %> 
    <%= form.select :sym_desc, options_for_select(@symptoms.collect{|u| [u.sym_desc]})%>
    <%= form.submit "Search" %>
  <% end %>
  <%= link_to "Reset", home_head_path, :style => "float: right; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block"%>
  <p>
  <strong><font size = "5">Solution:
  <strong>
    <%= @chosen_symptom %>
  </strong>
  </p>
   <p>
  Severity Level:
  <strong>
    <%= @severity %>
  </strong>
  </p>
  
   
</div>

src/app/views/home/index.html.erb
<%# <button type="button">Click Me!</button> %>
<%#= link_to "Results", home_results_path, class:"btn btn-secondary"%>
<h1>Off-Day Home</h1>
<br>

<%# Main Page #%>
<%= image_tag "body3.png", :style => "float: center; margin: 10px 10px 10px", height: 500 %>
<strong><font size = "9">Feeling off? Welcome to OFF-DAY! Please select the area on your body that is feeling Off and we will help you :)</strong> 
<%# PAGE LINKS #%>
<%= link_to "Head", home_head_path, :style => "float: center; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block "%>
<%= link_to "Arms", home_arms_path, :style => "float: center; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block"%>
<%= link_to "Core", home_core_path, :style => "float: center: margin: 0px 0px 10px" , class:"btn btn-secondary btn-lg btn-block"%>
<%= link_to "Legs", home_legs_path, :style => "float: center: margin: 0px 0px 10px" , class:"btn btn-secondary btn-lg btn-block"%>


   

src/app/views/home/legs.html.erb
<h1>Body Part: Legs</h1>

<div class = "center">
    <%= image_tag "legs3.png", :style => "float: left; margin: 100px 100px 100px", height: 720 %>
<br><br>
      <%= form_with model: @symptom, method: :get do |form| %> 
    <%= form.select :sym_desc, options_for_select(@symptoms.collect{|u| [u.sym_desc]})%>
    <%= form.submit "Search" %>
  <% end %>
  
  <p>
  <strong><font size = "5"> Solution:
  <strong>
    <%= @chosen_symptom %>
  </strong>
  </p>
   <p>
  Severity Level: 
  <strong>
    <%= @severity %>
  </strong>
  </p>
  <%= link_to "Reset", home_legs_path, :style => "float: right; margin: 0px 0px 10px", class:"btn btn-secondary btn-lg btn-block"%>
  
</div>

src/app/views/home/results.html.erb
<h1>Results..</h1>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# Bootstrap meta tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= app_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%# Bootstrap css %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body style = "background-color:pink">
    <%# Bootstrap js & dependencies %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%# Navigation Bar %>
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/"><%= app_name %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!---<li class="nav-item"> ADD THIS BACK TO EDIT DATABASE
            <a class="nav-link" href="/symptoms">Symtpoms Page</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
           
          </li>
          -->
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <br>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

src/app/views/symptoms/_form.html.erb
<%= form_with(model: symptom, local: true) do |form| %>
  <% if symptom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(symptom.errors.count, "error") %> prohibited this symptom from being saved:</h2>

      <ul>
        <% symptom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sym_desc %>
    <%= form.text_field :sym_desc %>
  </div>

  <div class="field">
    <%= form.label :sym_severity %>
    <%= form.number_field :sym_severity %>
  </div>

  <div class="field">
    <%= form.label :sym_location %>
    <%= form.text_field :sym_location %>
  </div>

    <div class="field">
    <%= form.label :solution %>
    <%= form.text_field :solution %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/symptoms/edit.html.erb
<h1>Editing Symptom</h1>

<%= render 'form', symptom: @symptom %>

<%= link_to 'Show', @symptom %> |
<%= link_to 'Back', symptoms_path %>

src/app/views/symptoms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Symptoms</h1>

<table>

  <thead>
    <tr>
      <th>Sym desc</th>
      <th>Sym severity</th>
      <th>Sym location</th>
      <th>Solution</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  

  <%= form_with model: @symptom, method: :get do |form| %> 
    <%= form.select :sym_desc, options_for_select(@symptoms.collect{|u| [u.sym_desc]})%>
    <%= form.submit "Search" %>
  <% end %>
  
  <p>
  Solution:
  <strong>
    <%= @chosen_symptom %>
  </strong>
  </p>
  
  
  <tbody>
    <% @symptoms.each do |symptom| %>
      <tr>
        <td><%= symptom.sym_desc %></td>
        <td><%= symptom.sym_severity %></td>
        <td><%= symptom.sym_location %></td>
        <td><%= symptom.solution %></td>
        <td><%= link_to 'Show', symptom %></td>
        <td><%= link_to 'Edit', edit_symptom_path(symptom) %></td>
        <td><%= button_to 'Destroy', symptom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody> 

</table>

<br>

<%= link_to 'New Symptom', new_symptom_path %>

src/app/views/symptoms/new.html.erb
<h1>New Symptom</h1>

<%= render 'form', symptom: @symptom %>

<%= link_to 'Back', symptoms_path %>

src/app/views/symptoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sym desc:</strong>
  <%= @symptom.sym_desc %>
</p>

<p>
  <strong>Sym severity:</strong>
  <%= @symptom.sym_severity %>
</p>

<p>
  <strong>Sym location:</strong>
  <%= @symptom.sym_location %>
</p>

<%= link_to 'Edit', edit_symptom_path(@symptom) %> |
<%= link_to 'Back', symptoms_path %>